# Generated by Django 3.1.7 on 2021-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=10)),
                ('goal_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
